
name: Build and Deploy Azure Apps Develop

on: workflow_dispatch

jobs:
  agionedev:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        AZURE_APPNAME: 'agionedev'
        WORKING_DIRECTORY: 'project-agione-backend/Platform'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

  agione-dev-hangfire:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        AZURE_APPNAME: 'agione-dev-hangfire'
        WORKING_DIRECTORY: 'project-agione-hangfire/agione-hangfire'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

  agionedev-laravel-sync:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        AZURE_APPNAME: 'agionedev-laravel-sync'
        WORKING_DIRECTORY: 'project-agione-laravel-sync/project-agione-laravel-sync'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

  agionedev-flighttracking-metrics:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        AZURE_APPNAME: 'agionedev-flighttracking-metrics'
        WORKING_DIRECTORY: 'project-agione-flightaware-metrics/FlyAwareMetrics'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

  agionedev-workday-posting-transactions:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        AZURE_APPNAME: 'agionedev-workday-posting-transactions'
        WORKING_DIRECTORY: 'project-agione-workday-poster-transactions/Agione-WorkdayFunctions'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit
    
  agionedev-workdaysync:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        AZURE_APPNAME: 'agionedev-workdaysync'
        WORKING_DIRECTORY: 'project-agione-workday-poster-transactions/Agione-WorkdayFunctions'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit


