# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deployment Azure Develop

on: workflow_dispatch     

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Cache dotnet
        uses: actions/cache@v3
        with:
         path: ~/.nuget/packages
         key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
         restore-keys: |
          ${{ runner.os }}-nuget-
          
      - name: Initialize submodules
        run: git submodule update --init --remote
      
      - name: Up to date master branch
        run: |
          git config --global user.name 'agionedev'
          git config --global user.email 'admin-dev01@allianceground.com'
          git fetch --unshallow
          git checkout develop
          git pull
          git submodule foreach --recursive git checkout develop
          git submodule foreach --recursive git pull
        
      - name: Restore dependencies
        run: dotnet restore 
          
      - name: Build with dotnet
        run: dotnet build "project-agione-backend/Platform" --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'agionedev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3BE715B7870E4538B590634A53DF0A56 }}
          package: .
