
name: Build and Deploy Azure Apps Develop

on: workflow_dispatch

jobs:
  agionedev:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        TARGET_ENV: 'Development'
        AZURE_APPNAME: 'agionedev'
        WORKING_DIRECTORY: 'project-agione-backend/Platform'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

  agione-dev-hangfire:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        TARGET_ENV: 'Development'
        AZURE_APPNAME: 'agione-dev-hangfire'
        WORKING_DIRECTORY: 'project-agione-hangfire/agione-hangfire'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

  agionedev-laravel-sync:
    uses: ./.github/workflows/reusable-deploy-azure-apps.yml
    with:
        TARGET_ENV: 'Development'
        AZURE_APPNAME: 'agionedev-laravel-sync'
        WORKING_DIRECTORY: 'project-agione-laravel-sync/project-agione-laravel-sync'
        DOTNET_VERSION: '6.0.x'
        CONFIGURATION: 'Release'
    secrets: inherit

